services:
  cli-relay:
    image: safezone-cli-relay:${VERSION:-latest}
    env_file:
      - ../.env.secret
    environment:
      - ENVIRONMENT=DEV
      - DB_URL=sqlite:////app/test.db
      - LOG_LEVEL=INFO
      # following env vars are not used
      - REPLICA_URL=sqlite:////app/test.db
      - REDIS_HOST=redis-state
      - REDIS_PORT=6379
      - REDIS_PASSWORD=5566
      - REDIS_DB=0
      - CACHE_HOST=redis-cache
      - CACHE_PORT=6379
      - CACHE_PASSWORD=5566
      - SIMULATOR_URL=http://pandemic-simulator:8000
      - INGESTOR_URL=http://data-ingestor:8000
      - ANALYTICS_API_URL=http://analytics-api:8000
      - DASHBOARD_URL=http://dashboard:8080
      - MKDOC_URL=http://mkdocs:8000
      - TIME_SERVER_URL=http://time-server:8000
      - ROLE_FILE=roles.example.yml
    profiles:
      - provision

  cli-daemon:
    image: safezone-cli-command:${VERSION:-latest}
    env_file:
      - ../.env.secret
    environment:
      - RELAY_URL=http://cli-relay:8000
      - RELAY_TIMEOUT=3600
    profiles:
      - provision
    depends_on:
      - cli-relay
